### ISSUE TITLE
Error when paying invoices generated by the same BTCpay server

### ISSUE THREAD

**Issue by anafaskrowten** [dennisreimann/btcpayserver-plugin-lnbank#14]
**Plugin**
LNBank v1.3.4.0

**Describe the bug**
Invoices generated by the BTCpay server that is also hosting the lightning wallet being used to pay the invoice, produces an API error "Impossible to find a route to the peer (Code 4)"

**To Reproduce the bug**
Create and load a balance to a LNbank wallet. Using the same BTCpay server, create a store and generate a lightning invoice. Use the LNbank wallet to pay the invoice. The same error occurs if you use the bluewallet app or if you use the LNbank webpage to pay the invoice.

**Screenshots**
![image](https://user-images.githubusercontent.com/102834026/195254868-a3614cd9-63dd-4052-8c76-ff3344841b0f.png)
![image](https://user-images.githubusercontent.com/102834026/195255290-5c0200da-c6b4-4927-92b2-ce27190237a7.png)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.6.12.0
- Lightning implementation  LND
- Deployment Method:  LunaNode
- Browser:   edge

**Logs (if applicable)**
[btcpay20221012.log](https://github.com/dennisreimann/btcpayserver/files/9761694/btcpay20221012.log)

**Comment by dennisreimann** [comment]
It might be the case that the [`allow-circular-route` property](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L423) needs to be configured. Our API calls allow for selt-payments, so this might be the hurdle.

Can you check the state of that property and eventually [edit your lnd.conf](https://docs.btcpayserver.org/FAQ/LightningNetwork/#how-to-edit-lndconf) like this:

```yaml
version: "3"
services:
  lnd_bitcoin:
    environment:
      LND_EXTRA_ARGS: |
        allow-circular-route=true
```

**Comment by dennisreimann** [comment]
Note to myself: Handle this but simply accepting the payment in case we detect self-payment:
- https://github.com/btcpayserver/BTCPayServer.Lightning/blob/master/src/BTCPayServer.Lightning.CLightning/CLightningClient.cs#L370
- https://github.com/btcpayserver/BTCPayServer.Lightning/blob/master/src/BTCPayServer.Lightning.LND/LndClient.cs#L698

**Comment by me639276639936** [comment]
even with these changes I cannot pay the LNbank invoice with the node’s invoice. I am not running Core Lightning 

![IMG_9989](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/134018025/c6848788-74cb-4f16-a5b7-86f608e9324b)
![IMG_9988](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/134018025/4c17df6d-cc6c-4e15-a0c4-f224f98f2151)
![IMG_9987](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/134018025/4485d4ed-11c9-4674-aa32-9d2fdfcbbe9e)

**Comment by dennisreimann** [comment]
@me639276639936 The second screenshot shows that you are passing the LNbank Transaction URL as a parameter instead of the BOLT11/Payment Request. That's the reason why it fails with the API route error.

If it still fails with the edited LND config: Did you run the setup script after adding the custom YML file?

**Comment by me639276639936** [comment]
Is the payment request called “Bech32”? If so I get the same error. In BlueWallet same error. In Lightning node it says payment sent but the payment never shows up in LNbank walletYes I ran the setup file after adding the ymlSent from my iPhoneOn May 19, 2023, at 2:13 AM, d11n ***@***.***> wrote:﻿
@me639276639936 The second screenshot shows that you are passing the LNbank Transaction URL as a parameter instead of the BOLT11/Payment Request. That's the reason why it fails with the API route error.
If it still fails with the edited LND config: Did you run the setup script after adding the custom YML file?

**Comment by me639276639936** [comment]
You can see the setting is successfully imported to lnd config in this RTL page tooSent from my iPhoneOn May 19, 2023, at 7:12 AM, Jace Longnecker ***@***.***> wrote:﻿Is the payment request called “Bech32”? If so I get the same error. In BlueWallet same error. In Lightning node it says payment sent but the payment never shows up in LNbank walletYes I ran the setup file after adding the ymlSent from my iPhoneOn May 19, 2023, at 2:13 AM, d11n ***@***.***> wrote:﻿
@me639276639936 The second screenshot shows that you are passing the LNbank Transaction URL as a parameter instead of the BOLT11/Payment Request. That's the reason why it fails with the API route error.
If it still fails with the edited LND config: Did you run the setup script after adding the custom YML file?

**Comment by me639276639936** [comment]
This issue resolved itself for some reason. Thanks!

**Comment by me639276639936** [comment]
Nevermind. This is failing again. 

In Bluewallet I tried sending from LND node to LNBank bech32 invoices and got this error again. 
![IMG_0125](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/134018025/b71eb9b0-0aaf-48e5-bd34-4315d39d0391)

I also tried just sending this in RTL but got the “you cant pay your own invoice error” again. 

Finally I tried to send from LND Node to LNBank LNURL (bech32) and got this error: 
![IMG_0127](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/134018025/cc1a38c7-6f6d-4b69-bddc-dc3bab0e1812)


Thoughts? Do I need to reinstall the custom yml for circular routing?

**Comment by me639276639936** [comment]
I even tried paying to your donate link and I get this error with LNBank and LND core 

![IMG_0128](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/134018025/9baebbbc-33cd-48b0-8cdf-39e57fd1fad4)

**Comment by me639276639936** [comment]
I just sent to wallet of satoshi via LNBank and also via LND Node and there was no issue.

**Comment by dennisreimann** [comment]
> I also tried just sending this in RTL but got the “you cant pay your own invoice error” again.

That might be an indicator that the `allow-circular-route` setting didn't get applied. 

> I even tried paying to your donate link and I get this error with LNBank and LND core

That's another problem though: the pathfinding between our nodes doesn't work out. 

> I just sent to wallet of satoshi via LNBank and also via LND Node and there was no issue.

Yes, that shows that outgoing liquidity is present, but that shouldn't even be a matter when sending to yourself. 

I'm at BTCPrague right now and will double-check my settings once back home.

**Comment by me639276639936** [comment]
So I reinstalled the custom yml. I can pay myself now. Yay!!!

but I still cant pay you via your btcpay donate button. Api Route error 4. 

Have fun in Prague. Thanks for your patience.
